### ISSUE TITLE
Would you be willing to offer guidance?

### ISSUE THREAD

**Issue by rocketman-pat** [GuillaumeFalourd/sign-and-notarize-gha#1]
We're having trouble getting this configured properly in our GitHub Actions pipeline. Are you accepting consultation calls? If so, what is your rate? We'd really appreciate your help!

Também sou brasileiro!

**Comment by GuillaumeFalourd** [comment]
Hi @rocketman-pat , how are you doing? 😃 

I would be happy to help. Could you share some context about the issue you are facing? You can share it here or send it to me through email 👍🏼

**Comment by rocket-victor** [comment]
Hi! Thanks for offering to help. 😃

We're encountering an issue with the notarization of our .pkg installer for a Python-based macOS application. The main challenge seems to stem from the initial signing of the binary contents within the .pkg. Here's a brief overview:

1. **Code Signing**: We use PyInstaller to build the executable and then package it into a .pkg using `pkgbuild`. While we do sign the .pkg itself, we're uncertain if we're correctly signing all necessary binary and executable contents within the .pkg prior to this step.
2. **Notarization Fails**: The notarization process via `xcrun notarytool` consistently fails, leading us to suspect that the issue could be due to the initial signing of the contents. This is critical as improperly signed contents could be why notarization rejects the package.
3. **Workflow Configuration**: Our GitHub Actions setup automates the build, sign, and notarization processes. It includes steps for creating a macOS-specific keychain for code signing, and managing security for certificate handling.

Here's the concern: Are we missing a step or misconfiguring the signing of the binary/executable contents before creating the .pkg? Any guidance on ensuring all components are correctly signed before packaging would be hugely helpful.

Part of our github action:

```yml
- name: Import developer id installer certificate
  uses: apple-actions/import-codesign-certs@v1
  with:
    p12-file-base64: ${{ secrets.DEVELOPER_ID_INSTALLER_KEY }}
    p12-password: ${{ secrets.INSTALLER_P12_PASSWORD }}
    keychain: build
    keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

- name: Import developer id application certificate
  uses: apple-actions/import-codesign-certs@v1
  with:
    p12-file-base64: ${{ secrets.DEVELOPER_ID_APPLICATION_KEY }}
    p12-password: ${{ secrets.APPLICATION_P12_PASSWORD }}
    create-keychain: false
    keychain: build
    keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

- name: Verify certificates on Keychain
  run: |     
    # Verify certificates on Keychain
    security list-keychain -d user -s build.keychain
    security find-identity -v -p codesigning

- name: "Generate signed pkg"
  run: |
    # Create a binary executable
    pyinstaller main.py \
      --name rocketman \
      --add-data "version.txt:." \
      --add-binary "/usr/local/bin/dialog:." \
      --osx-bundle-identifier "${{ secrets.BUNDLE_ID }}" \
      --codesign-identity "${{ secrets.DEVELOPER_ID_APPLICATION_NAME }}"
    chmod -R a+rw ./dist/rocketman

    # Create a pkg installer
    pkgbuild \
      --root ./dist/rocketman \
      --install-location /usr/local/bin \
      --identifier "${{ secrets.BUNDLE_ID }}" \
      --version "${{ env.TAG }}" \
      "unsigned.pkg"
    
    # Sign PKG file
    productsign \
      --sign "${{ secrets.DEVELOPER_ID_INSTALLER_NAME }}" \
      "unsigned.pkg" \
      "signed.pkg"

- name: Verify Signature
  run: |
    pkgutil --check-signature "signed.pkg"

- name: Notarize PKG
  run: |
    xcrun notarytool store-credentials "notarytool-profile" \
        --apple-id "${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}" \
        --password "${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}" \
        --team-id "${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}"

    xcrun notarytool submit "signed.pkg" \
        --keychain-profile "notarytool-profile" \
        --wait
    
    # Staple the notarization
    xcrun stapler staple "signed.pkg"

- name: Verify Notarization
  run: |
    spctl --assess -vv --type install "signed.pkg"
```

At moment we get this error:
```
Conducting pre-submission checks for signed.pkg and initiating connection to the Apple notary service...
Submission ID received
  id: e2966351-4496-4833-898f-de01274151d0
Successfully uploaded file
  id: e2966351-4496-4833-898f-de01274151d0
  path: /Users/runner/work/rocketman-command-center/rocketman-command-center/signed.pkg
Waiting for processing to complete.
Current status: In Progress...
Current status: In Progress....
Current status: In Progress.....
Current status: In Progress......
Current status: In Progress.......
Current status: In Progress........
Current status: Invalid.........Processing complete
  id: e2966351-4496-4833-898f-de01[27](https://github.com/Rocketman-Tech/rocketman-command-center/actions/runs/11694925741/job/32569471132#step:16:28)4151d0
  status: Invalid
Processing: /Users/runner/work/rocketman-command-center/rocketman-command-center/signed.pkg
CloudKit query for signed.pkg (1/e4486a45b78652766f8a863a86768ca07fb4ec09) failed due to "Record not found".
Could not find base64 encoded ticket in response for 1/e4486a45b78652766f8a863a86768ca07fb4ec09
The staple and validate action failed! Error 65.
```

xcrun notarytool log e2966351-4496-4833-898f-de01 --keychain-profile "notarytool-profile"

```
Error: No Keychain password item found for profile: notarytool-profile

Run 'notarytool store-credentials' to create another credential profile.
```

**Comment by GuillaumeFalourd** [comment]
I never used pyinstaller for the code signing, so I don't know how it behaves :/

However, I used to code sign python files through a script during my CI/CD process, which seems similar, and guaranteed at the time that all my files were signed. You can find the script here if you want to try it: https://gist.github.com/GuillaumeFalourd/4efc73f1a6014b791c0ef223a023520a (it's also on the README file example).

It also seems that you didn't get the log due to some credential issues. Where did you run the `xcrun notarytool log ...` command line? Was it in the same workflow where the notarization failed? (it seems not, but it would be worth adding it there).

_Note: I've also created an action we use internally at the company I'm working at for the notarization and the staple if you want to experiment (https://github.com/GuillaumeFalourd/notary-tools), I didn't add the troubleshooting part with the notarytool log command, but it could be a new feature improvement to implement._

**Comment by rocket-victor** [comment]
Thank you, your [script](https://gist.github.com/GuillaumeFalourd/4efc73f1a6014b791c0ef223a023520a) help me a lot to make all work

**Comment by rocket-victor** [comment]
I've come across another problem, I don't know if you've already encountered it, but basically pkgbuild doesn't support binaries signed with the codesign flag --options=runtime and this is preventing it from notorizing. Do you have any idea how to create a pkg from a folder in which the binary has been signed in this way?

The executable does not have the hardened runtime enabled.

**Comment by GuillaumeFalourd** [comment]
Did you try adding the `--sign "Developer ID Installer: Your Name (TeamID)"` argument to the `pkgbuild` command line? Using the same Developer ID installer used in the `codesign` command execution (in the script)?

```sh
    # Create a pkg installer
    pkgbuild \
      --root ./dist/rocketman \
      --install-location /usr/local/bin \
      --identifier "${{ secrets.BUNDLE_ID }}" \
      --sign "Developer ID Installer: Your Name (TeamID)"\.  # Adding this line
      --version "${{ env.TAG }}" \
      "unsigned.pkg"
```

**Comment by rocket-victor** [comment]
yes we are using this --sign, but the codesign command we are using "Developer ID Application: ..."

```yml
- name: Import developer id installer certificate
  uses: apple-actions/import-codesign-certs@v1
  with:
    p12-file-base64: ${{ secrets.DEVELOPER_ID_INSTALLER_KEY }}
    p12-password: ${{ secrets.INSTALLER_P12_PASSWORD }}
    keychain: build
    keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

- name: Import developer id application certificate
  uses: apple-actions/import-codesign-certs@v1
  with:
    p12-file-base64: ${{ secrets.DEVELOPER_ID_APPLICATION_KEY }}
    p12-password: ${{ secrets.APPLICATION_P12_PASSWORD }}
    create-keychain: false
    keychain: build
    keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

- name: Verify certificates on Keychain
  run: |     
    # Verify certificates on Keychain
    security find-identity -v -p basic

- name: "Generate binary"
  run: |
    # Create a binary executable
    source .venv/bin/activate
    pyinstaller main.py \
      --name rocketman \
      --add-data "version.txt:." \
      --add-binary "dialog:."

- name: Sign all files
  run: |
    sh codesign.sh "${{ secrets.DEVELOPER_ID_APPLICATION_NAME }}" "${{ secrets.BUNDLE_ID }}"

- name: "Test binary after sign all files"
  run: |
    ./dist/rocketman/rocketman -v

- name: Create a pkg installer signed
  run: |
    pkgbuild \
      --root ./dist/rocketman \
      --install-location /usr/local/bin \
      --identifier "${{ secrets.BUNDLE_ID }}" \
      --version "${{ env.TAG }}" \
      --sign "${{ secrets.DEVELOPER_ID_INSTALLER_NAME }}" \
      "unsigned.pkg"

- name: Sign package again with productsign
  run: |
    productsign --sign "${{ secrets.DEVELOPER_ID_INSTALLER_NAME }}" unsigned.pkg signed.pkg

- name: Verify Signature
  run: |
    pkgutil --check-signature "signed.pkg"

- name: Notarize PKG
  run: |
    xcrun notarytool store-credentials "notarytool-profile" \
      --apple-id "${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}" \
      --password "${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}" \
      --team-id "${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}"

    output=$(xcrun notarytool submit "signed.pkg" --keychain-profile "notarytool-profile" --wait)
    echo $output

    extracted_id=$(echo "$output" | awk '/status: Invalid/ {getline; if ($1 == "id:") print $2}')

    if [ -n "$extracted_id" ]; then
      echo "ID: $extracted_id"
      xcrun notarytool log $extracted_id --keychain-profile "notarytool-profile"
      exit 1
    else
      # Staple the notarization
      xcrun stapler staple "signed.pkg"
    fi

- name: Verify Notarization
  run: |
    spctl --assess -vv --type install "signed.pkg"
```

Arquivo codesign.sh

```sh
#!/bin/bash

DEVELOPER_ID_APP=$1
BUNDLE_ID=$2
export "DEVELOPER_ID_APP=$DEVELOPER_ID_APP"
export "BUNDLE_ID=$BUNDLE_ID"

signFile() {
  filename=$1

  if [ -f "$filename" ]; then
    echo "Signing FILE: $filename"
    codesign -dvvvv -s "$DEVELOPER_ID_APP" -f --timestamp -i "$BUNDLE_ID" -o runtime "$filename"
    codesign -vvv --deep --strict "$filename"
  else
    echo "Skipping directory: $filename"
  fi
}

export -f signFile
find ./dist/rocketman -exec bash -c 'signFile "{}"' \;
```
